### ISSUE TITLE
500 Errors

### ISSUE THREAD

**Issue by victoria34** [dfci/matchminer-ui#1]
After I built up matchminer-ui and matchminer-api instances, the ui instance has errors below in Network tab of console. Could you give me any suggestions? Thanks!

![screen shot 2018-07-02 at 2 54 11 pm](https://user-images.githubusercontent.com/14971266/42181183-fc7ffb40-7e07-11e8-8e15-d14b9d6d0c19.png)

![screen shot 2018-07-02 at 2 54 32 pm](https://user-images.githubusercontent.com/14971266/42181186-009f0964-7e08-11e8-8dae-1f501159b23d.png)

**Comment by jim-bo** [comment]
Hi Victoria, can you get the API server logs? If you are running it in development mode they should be printed to console.
