### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-ui#4]
Mac OS X El Capitan 10.11.6

After cloning tried to run docker build and got this:

(matchminer-ui) host011:~/matchminer-ui$ docker build - < Dockerfile
Sending build context to Docker daemon   2.56kB
Step 1/11 : FROM node:7-onbuild
7-onbuild: Pulling from library/node
ad74af05f5a2: Pull complete
2b032b8bbe8b: Pull complete
a9a5b35f6ead: Pull complete
3245b5a1c52c: Pull complete
afa075743392: Pull complete
9fb9f21641cd: Pull complete
3f40ad2666bc: Pull complete
49c0ed396b49: Pull complete
7af304825012: Pull complete
Digest: sha256:e506d4de7f21fc0cf51e2d2f922eb0349bd2c07f39dd6335e4338f92c9408994
Status: Downloaded newer image for node:7-onbuild
# Executing 5 build triggers
 ---> Running in f8af68cce253
Removing intermediate container f8af68cce253
 ---> Running in b6b414099107
Removing intermediate container b6b414099107
COPY failed: stat /var/lib/docker/tmp/docker-builder185737831/package.json: no such file or directory

**Comment by ethansiegl** [comment]
looks like there isn't a dist folder. try running this command to create a UI ```/dist``` folder before running docker build

```gulp --env production build```

**Comment by cegg** [comment]
The suggested command runs successfully. dist directory gets created
$ docker build . gulp --env production build
$ ls -la dist
total 376
drwxr-xr-x   6 igorpozdnyakov  staff     192 Oct 16 11:49 .
drwxr-xr-x  22 igorpozdnyakov  staff     704 Oct 16 11:50 ..
-rwxr-xr-x   1 igorpozdnyakov  staff    1150 Oct 16 11:49 favicon.ico
drwxr-xr-x   7 igorpozdnyakov  staff     224 Oct 16 11:49 images
-rw-r--r--   1 igorpozdnyakov  staff  180538 Oct 16 11:49 npm-debug.log
-rwxr-xr-x   1 igorpozdnyakov  staff      43 Oct 16 11:49 robots.txt

However, docker build still fails:
$ docker build -t matchminer-ui .
.
.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2
(node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current:
{"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
(node_modules/mdast/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current:
{"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
(node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current:
{"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
(node_modules/karma/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current:
{"os":"linux","arch":"x64"})
npm WARN jit-grunt@0.9.1 requires a peer of grunt@~0.4.0 but none was
installed.
npm ERR! Linux 4.9.93-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node
install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the
phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-10-16T10_03_16_388Z-debug.log

my node version is v8.12.0
my npm version is 6.4.1

**Comment by cegg** [comment]
Also:
*gulp test* now works
However, *gulp serve* gives this error about certificate:

$ gulp serve
[12:58:21] Using gulpfile ~/matchminer-ui/gulpfile.js
[12:58:21] Starting 'config'...
[12:58:21] Starting 'load-templates'...
[12:58:21] Starting 'scripts'...
[12:58:21] Starting 'styles'...
[12:58:21] Finished 'config' after 654 ms
[12:58:21] Finished 'load-templates' after 646 ms
[12:58:21] gulp-inject 34 files into matchminer.less.
[12:58:22] Finished 'styles' after 1.19 s
[12:58:23] all files 543.3 kB
[12:58:23] Finished 'scripts' after 2.1 s
[12:58:23] Starting 'inject'...
[12:58:23] gulp-inject 1 files into index.html.
[12:58:23] gulp-inject 92 files into index.html.
[12:58:23] Finished 'inject' after 218 ms
[12:58:23] Starting 'watch'...
[12:58:23] Finished 'watch' after 111 ms
[12:58:23] Starting 'serve'...
[12:58:23] 'serve' errored after 385 μs
[12:58:23] Error: ENOENT: no such file or directory, open
'../certificates/matchminer.key'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at browserSyncInit
(/Users/igorpozdnyakov/matchminer-ui/gulp/server.js:52:12)
    at Gulp.<anonymous>
(/Users/igorpozdnyakov/matchminer-ui/gulp/server.js:100:2)
    at module.exports
(/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask
(/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep
(/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/index.js:214:10)
    at
/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/index.js:279:18
    at finish
(/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports
(/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask
(/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep
(/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/index.js:214:10)
    at
/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/index.js:279:18
    at finish
(/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/lib/runTask.js:21:8)
    at
/Users/igorpozdnyakov/matchminer-ui/node_modules/orchestrator/lib/runTask.js:52:4
    at f
(/Users/igorpozdnyakov/matchminer-ui/node_modules/end-of-stream/node_modules/once/once.js:17:25)
